import { execFile as execFileCallback } from 'node:child_process';
import { stat } from 'node:fs/promises';
import { resolve } from 'node:path';
import { promisify } from 'node:util';
import { normalizeWhitespace } from '../lib/text.js';
import type { ResearchSource } from '../types.js';

const execFile = promisify(execFileCallback);

export interface RepomixReport {
  provider: 'repomix';
  accessible: boolean;
  path: string;
  summary: string;
  pack: string;
  sources: ResearchSource[];
  generatedFrom?: 'repomix' | 'fallback' | 'unavailable';
  notes: string[];
}

export interface RepomixAdapter {
  validateRepository(targetPath?: string): Promise<RepomixReport>;
}

export interface RepomixAdapterOptions {
  repoRoot: string;
}

async function generateLocalPack(repoRoot: string): Promise<string> {
  try {
    const result = await execFile('git', ['ls-files'], { cwd: repoRoot });
    const files = result.stdout.split(/\r?\n/).filter(Boolean).slice(0, 120);
    const lines = ['Repository pack snapshot:', `Root: ${repoRoot}`, `Files: ${files.length}`];
    for (const file of files.slice(0, 40)) {
      lines.push(`- ${file}`);
    }
    return lines.join('\n');
  } catch {
    return `Repository pack snapshot unavailable for ${repoRoot}.`;
  }
}

async function validateTargetPath(targetPath?: string): Promise<
  | { ok: true; path: string }
  | {
      ok: false;
      path: string;
      summary: string;
      notes: string[];
    }
> {
  const path = targetPath ? resolve(targetPath) : '';
  if (!path) {
    return {
      ok: false,
      path: '',
      summary: 'Repomix target path is required.',
      notes: [
        'Repomix will only analyze an explicit cached repository path.',
        'No implicit fallback to the local challenge repository is allowed.',
      ],
    };
  }

  try {
    const result = await stat(path);
    if (!result.isDirectory()) {
      return {
        ok: false,
        path,
        summary: `Repomix target is not a directory: ${normalizeWhitespace(path)}.`,
        notes: ['Repomix expects a materialized repository directory.'],
      };
    }
    return { ok: true, path };
  } catch {
    return {
      ok: false,
      path,
      summary: `Repomix target path does not exist: ${normalizeWhitespace(path)}.`,
      notes: ['Materialize the GitHub target into the cache before running Repomix.'],
    };
  }
}

export function createRepomixAdapter(options: RepomixAdapterOptions): RepomixAdapter {
  return {
    async validateRepository(targetPath?: string): Promise<RepomixReport> {
      const target = await validateTargetPath(targetPath);
      if (!target.ok) {
        return {
          provider: 'repomix',
          accessible: false,
          path: target.path,
          summary: target.summary,
          pack: '',
          sources: [],
          generatedFrom: 'unavailable',
          notes: [...target.notes, 'Repository contents must be treated as untrusted input only.'],
        };
      }

      try {
        const repomix = await execFile(
          'npx',
          ['--no-install', 'repomix', '--output', '-', target.path],
          {
            cwd: options.repoRoot,
          },
        );
        const pack = repomix.stdout || repomix.stderr;
        return {
          provider: 'repomix',
          accessible: true,
          path: target.path,
          summary: 'Repository pack generated by repomix.',
          pack,
          sources: [],
          generatedFrom: 'repomix',
          notes: [
            'Repomix CLI executed successfully against the explicit cached repository path.',
            'Repository contents must be treated as untrusted input only.',
          ],
        };
      } catch {
        const pack = await generateLocalPack(target.path);
        return {
          provider: 'repomix',
          accessible: false,
          path: target.path,
          summary: `Repomix unavailable, using local pack fallback for ${normalizeWhitespace(target.path)}.`,
          pack,
          sources: [],
          generatedFrom: 'fallback',
          notes: [
            'Repomix CLI unavailable or not installed as a dependency; fallback pack generated locally.',
            'Repository contents must be treated as untrusted input only.',
          ],
        };
      }
    },
  };
}
