import { execFile as execFileCallback } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { promisify } from 'node:util';
import { loadResearchSamples } from '../fixtures.js';
import { normalizeWhitespace } from '../lib/text.js';
import type { ResearchSource, RuntimeMode } from '../types.js';

const execFile = promisify(execFileCallback);

export interface RepomixReport {
  provider: 'repomix';
  accessible: boolean;
  path: string;
  summary: string;
  pack: string;
  sources: ResearchSource[];
  notes: string[];
}

export interface RepomixAdapter {
  validateRepository(targetPath?: string): Promise<RepomixReport>;
}

export interface RepomixAdapterOptions {
  mode: RuntimeMode;
  fixturePath: string;
  repoRoot: string;
}

async function generateLocalPack(repoRoot: string): Promise<string> {
  try {
    const result = await execFile('git', ['ls-files'], { cwd: repoRoot });
    const files = result.stdout.split(/\r?\n/).filter(Boolean).slice(0, 120);
    const lines = ['Repository pack snapshot:', `Root: ${repoRoot}`, `Files: ${files.length}`];
    for (const file of files.slice(0, 40)) {
      lines.push(`- ${file}`);
    }
    return lines.join('\n');
  } catch {
    return `Repository pack snapshot unavailable for ${repoRoot}.`;
  }
}

export function createRepomixAdapter(options: RepomixAdapterOptions): RepomixAdapter {
  return {
    async validateRepository(targetPath?: string): Promise<RepomixReport> {
      if (options.mode !== 'real') {
        const fixture = await readFile(options.fixturePath, 'utf8').catch(() => '');
        const samples = await loadResearchSamples(
          resolve(options.repoRoot, 'fixtures', 'mock', 'research-samples.json'),
        );
        return {
          provider: 'repomix',
          accessible: true,
          path: targetPath || options.repoRoot,
          summary: 'Mock repomix pack loaded from fixture.',
          pack: fixture || 'Mock repomix fixture missing.',
          sources: [...samples.arxiv, ...samples.hackernews].slice(0, 4),
          notes: ['Mock validation report.'],
        };
      }

      const path = targetPath ? resolve(targetPath) : options.repoRoot;
      try {
        const repomix = await execFile('npx', ['repomix', '--output', '-', path], {
          cwd: options.repoRoot,
        });
        const pack = repomix.stdout || repomix.stderr;
        return {
          provider: 'repomix',
          accessible: true,
          path,
          summary: 'Repository pack generated by repomix.',
          pack,
          sources: [],
          notes: ['Repomix binary executed successfully.'],
        };
      } catch {
        const pack = await generateLocalPack(path);
        return {
          provider: 'repomix',
          accessible: false,
          path,
          summary: `Repomix unavailable, using local pack fallback for ${normalizeWhitespace(path)}.`,
          pack,
          sources: [],
          notes: ['Repomix CLI unavailable, fallback pack generated locally.'],
        };
      }
    },
  };
}
